apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  namespace: default  # change if using another namespace
spec:
  type: LoadBalancer
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      volumeMounts:
      - name: elastic-config
        mountPath: /config
  volumes:
   - name: elasticsearch-config
     persistentVolumeClaim:
     claimName: elasticsearch-pvc
