apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: default
spec:
  version: 8.12.0  # Specify your desired Elasticsearch version
  nodeSets:
    - name: default
      count: 3  # Number of Elasticsearch nodes in the cluster
      config:
        node.store.allow_mmap: false
