apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
    - containerPort: 9200
    - containerPort: 9300
    env:
    - name: discovery.type
      value: single-node
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    volumeMounts:
    - name: es-data
      mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: es-data
    emptyDir: {}

     
