apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: http
    - protocol: TCP
    - port: 9200
      targetPort: 9200
    - name: Transport
    - protocol: TCP
    - port: 9300
      targetPort: 9300
       app: elasticsearch

