apiVersion: apps/V1
kind: Deployment
Metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend  
spec:
  replicas: 3
  selector:
    matchlabels:
     app: frontend
  template:
    Metadata:
       labels:
         app: frontend
         tier: frontend
    spec:
      containers:
        - name: frontend
          image: #image path
          ports:
            - containerPort: 8080 # port for containerport
        
