apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
      - name: homarr
        image: ghcr.io/ajnart/homarr:latest
        ports:
        - containerPort: 7575
        volumeMounts:
        - name: homarr-config
          mountPath: /config
      volumes:
      - name: homarr-config
        persistentVolumeClaim:
          claimName: homarr-pvc
