apiVersion: v1
kind: Pod
metadata:
  name: homarr
spec:
  containers:
    - name: homarr
      image: ghcr.io/ajnart/homarr:latest
      ports:
        - containerPort: 7575
     volumeMounts:
       - mountPath: "/data"
          name: homarr-storage
  volumes:
    - name: homarr-storage
      persistentVolumeClaim:
        claimName: homarr-pvc

