apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:latest
        ports:
          - containerPort: 9000
        env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: BASE_URL
              value: "http://localhost:9000"
        volumeMounts:
        - name: mealie-storage
          mountPath: /app/data
      volumes:
      - name: mealie-storage
        persistentVolumeClaim:
          claimName: mealie-data
