apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/ajnart/homarr:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: mealie-config
          mountPath: /config
      volumes:
      - name: mealie-config
        persistentVolumeClaim:
          claimName: mealie-data-pvc.yaml
