apiVersion: v1
kind: PersistentVolume
metadata:
  name: name for volume -pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/podname"
