clusterName: elasticsearch-cluster
nodeGroup: master

roles:
  master: "true"
  ingest: "true"
  data: "true"

replicas: 4

esConfig:
  elasticsearch.yml: |
    cluster.name: my-elasticsearch-cluster
    node.name: es-node-1
    discovery.seed_hosts: ["es-node-1", "es-node-2", "es-node-3" ,"es-node-4"]
    cluster.initial_master_nodes: ["es-node-1", "es-node-2", "es-node-3" ,"es-node-4" ]

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
