clusterName: "my-elasticsearch-cluster"
nodeGroup: "master"

roles:
  master: "true"
  ingest: "true"
  data: "true"

replicas: 3

esConfig:
  elasticsearch.yml: |
    cluster.name: "my-elasticsearch-cluster"
    node.name: "node-1"
    discovery.seed_hosts: ["node-1", "node-2", "node-3"]
    cluster.initial_master_nodes: ["node-1", "node-2", "node-3"]

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
